import type { Metadata } from "next";
import { Gentium_Plus, Geist_Mono } from "next/font/google";
import "./globals.css";

const gentiumPlus = Gentium_Plus({
  variable: "--font-gentium-plus",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gentiumPlus.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
